### ISSUE TITLE
recompose-relay's peerDependencies are very outdated

### ISSUE THREAD

**Issue by AndrewIngram** [acdlite/recompose#121]
I can't tell if the library is abandoned or not, but the broken peerDependencies are preventing me from using npm shrinkwrap.

**Comment by acdlite** [comment]
It's not abandoned. I need to update the release script to automatically bump those deps :( I'll try do this soon.

**Comment by acdlite** [comment]
Fixed in latest release

**Comment by AndrewIngram** [comment]
The latest release requires a peer dependency of react-relay@^0.6.0, but the latest version is 0.7.3, so the check is still failing.

**Comment by filod** [comment]
@AndrewIngram use npm 3 will solve your problem (in this case)

**Comment by AndrewIngram** [comment]
I'm already using npm 3, shrinkwrap will fail if you have invalid peer dependencies

Relay is now up to 0.8.1, recompose-relay still depends on 0.6.0.

Should the version string look like this?

```
>=0.4.0 <0.9.0
```

**Comment by justinanastos** [comment]
It appears as though this is still an issue and should be re-opened.

https://github.com/acdlite/recompose/blob/master/src/packages/recompose-relay/package.json#L23

>"react-relay": "^0.6.0"

**Comment by justinanastos** [comment]
I should have checked the PRs first. There's an open PR to resolve this issue #234
